# Generated by Django 4.2 on 2023-04-08 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Historico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
                ('emails', models.TextField()),
                ('setor', models.CharField(max_length=150)),
                ('data_hora', models.DateTimeField()),
            ],
        ),
    ]
