# Generated by Django 4.2 on 2023-04-09 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_historico'),
    ]

    operations = [
        migrations.AddField(
            model_name='historico',
            name='emails_enviados',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
