# Generated by Django 4.2 on 2023-04-09 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_historico_emails_enviados'),
    ]

    operations = [
        migrations.AddField(
            model_name='historico',
            name='falharam',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='historico',
            name='passaram',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
