# Generated by Django 4.2 on 2023-04-10 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_historico_falharam_historico_passaram'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agendados',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
                ('emails', models.TextField()),
                ('setor', models.CharField(max_length=150)),
                ('template', models.TextField()),
                ('data_hora', models.TextField()),
            ],
        ),
    ]
