# Generated by Django 4.2 on 2023-04-15 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_agendados'),
    ]

    operations = [
        migrations.CreateModel(
            name='Templates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
                ('body', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='agendados',
            name='data_hora',
            field=models.DateTimeField(),
        ),
    ]
