# Generated by Django 4.2 on 2023-04-27 03:22

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_historicoindiv'),
    ]

    operations = [
        migrations.AddField(
            model_name='historico',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
