# Generated by Django 4.2 on 2023-04-30 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_rastreiopixel'),
    ]

    operations = [
        migrations.AddField(
            model_name='rastreiopixel',
            name='aberto',
            field=models.BooleanField(default=False),
        ),
    ]
