# Generated by Django 4.2 on 2023-04-30 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_rastreiopixel_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicoindiv',
            name='abriu',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
