# Generated by Django 4.2 on 2023-04-30 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_historicoindiv_abriu'),
    ]

    operations = [
        migrations.AddField(
            model_name='historico',
            name='abriram',
            field=models.IntegerField(default=0),
        ),
    ]
