# Generated by Django 4.2 on 2023-04-30 01:51

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_historico_abriram'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rastreiopixel',
            name='id',
        ),
        migrations.AlterField(
            model_name='rastreiopixel',
            name='id_pixel',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
