# Generated by Django 4.2 on 2023-04-30 02:35

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_remove_rastreiopixel_id_alter_rastreiopixel_id_pixel'),
    ]

    operations = [
        migrations.CreateModel(
            name='RastreioLink',
            fields=[
                ('id_link', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nome_campanha', models.TextField()),
                ('email', models.TextField()),
                ('aberto', models.BooleanField(default=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
